//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by SlSvcUtil, version 5.0.61118.0
// 
namespace WcfServiceItem
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceItem")]
    public partial class CompositeType : object
    {
        
        private string ItemCodeField;
        
        private string ItemDescField;
        
        private double PriceField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemCode
        {
            get
            {
                return this.ItemCodeField;
            }
            set
            {
                this.ItemCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemDesc
        {
            get
            {
                return this.ItemDescField;
            }
            set
            {
                this.ItemDescField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Price
        {
            get
            {
                return this.PriceField;
            }
            set
            {
                this.PriceField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ItemCode", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceItem")]
    public partial class ItemCode : object
    {
        
        private string ICodeField;
        
        private string IDescField;
        
        private double PriceField;
        
        private string UOMField;
        
        private bool isincludesiveField;
        
        private double taxField;
        
        private string taxgrpField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ICode
        {
            get
            {
                return this.ICodeField;
            }
            set
            {
                this.ICodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IDesc
        {
            get
            {
                return this.IDescField;
            }
            set
            {
                this.IDescField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Price
        {
            get
            {
                return this.PriceField;
            }
            set
            {
                this.PriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UOM
        {
            get
            {
                return this.UOMField;
            }
            set
            {
                this.UOMField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isincludesive
        {
            get
            {
                return this.isincludesiveField;
            }
            set
            {
                this.isincludesiveField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double tax
        {
            get
            {
                return this.taxField;
            }
            set
            {
                this.taxField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string taxgrp
        {
            get
            {
                return this.taxgrpField;
            }
            set
            {
                this.taxgrpField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Customer", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceItem")]
    public partial class Customer : object
    {
        
        private string Addr1Field;
        
        private string Addr2Field;
        
        private string Addr3Field;
        
        private string Addr4Field;
        
        private string CustomerCodeField;
        
        private string CustomerNameField;
        
        private string FaxField;
        
        private string GstField;
        
        private string PayCodeField;
        
        private string TelField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Addr1
        {
            get
            {
                return this.Addr1Field;
            }
            set
            {
                this.Addr1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Addr2
        {
            get
            {
                return this.Addr2Field;
            }
            set
            {
                this.Addr2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Addr3
        {
            get
            {
                return this.Addr3Field;
            }
            set
            {
                this.Addr3Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Addr4
        {
            get
            {
                return this.Addr4Field;
            }
            set
            {
                this.Addr4Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerCode
        {
            get
            {
                return this.CustomerCodeField;
            }
            set
            {
                this.CustomerCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerName
        {
            get
            {
                return this.CustomerNameField;
            }
            set
            {
                this.CustomerNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fax
        {
            get
            {
                return this.FaxField;
            }
            set
            {
                this.FaxField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Gst
        {
            get
            {
                return this.GstField;
            }
            set
            {
                this.GstField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PayCode
        {
            get
            {
                return this.PayCodeField;
            }
            set
            {
                this.PayCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tel
        {
            get
            {
                return this.TelField;
            }
            set
            {
                this.TelField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompanyProfile", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceItem")]
    public partial class CompanyProfile : object
    {
        
        private string Addr1Field;
        
        private string Addr2Field;
        
        private string Addr3Field;
        
        private string Addr4Field;
        
        private bool AllowClrTrxHisField;
        
        private bool AllowDeleteField;
        
        private bool AllowEditField;
        
        private string CNPrefixField;
        
        private int CNRunNoField;
        
        private string CompanyNameField;
        
        private string DOPrefixField;
        
        private int DORunNoField;
        
        private string FaxField;
        
        private string GSTNoField;
        
        private string HomeCurrField;
        
        private bool IsCustByAgentField;
        
        private bool IsInclusiveField;
        
        private bool NoEditAfterPrintField;
        
        private string PrefixField;
        
        private string RegNoField;
        
        private int RunNoField;
        
        private string SOPrefixField;
        
        private int SORunNoField;
        
        private int SalesTaxDecField;
        
        private bool ShowPrintTimeField;
        
        private string SupportContatField;
        
        private string TelField;
        
        private string WCFUrlField;
        
        private string WareHouseField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Addr1
        {
            get
            {
                return this.Addr1Field;
            }
            set
            {
                this.Addr1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Addr2
        {
            get
            {
                return this.Addr2Field;
            }
            set
            {
                this.Addr2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Addr3
        {
            get
            {
                return this.Addr3Field;
            }
            set
            {
                this.Addr3Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Addr4
        {
            get
            {
                return this.Addr4Field;
            }
            set
            {
                this.Addr4Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool AllowClrTrxHis
        {
            get
            {
                return this.AllowClrTrxHisField;
            }
            set
            {
                this.AllowClrTrxHisField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool AllowDelete
        {
            get
            {
                return this.AllowDeleteField;
            }
            set
            {
                this.AllowDeleteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool AllowEdit
        {
            get
            {
                return this.AllowEditField;
            }
            set
            {
                this.AllowEditField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CNPrefix
        {
            get
            {
                return this.CNPrefixField;
            }
            set
            {
                this.CNPrefixField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CNRunNo
        {
            get
            {
                return this.CNRunNoField;
            }
            set
            {
                this.CNRunNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CompanyName
        {
            get
            {
                return this.CompanyNameField;
            }
            set
            {
                this.CompanyNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DOPrefix
        {
            get
            {
                return this.DOPrefixField;
            }
            set
            {
                this.DOPrefixField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DORunNo
        {
            get
            {
                return this.DORunNoField;
            }
            set
            {
                this.DORunNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fax
        {
            get
            {
                return this.FaxField;
            }
            set
            {
                this.FaxField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GSTNo
        {
            get
            {
                return this.GSTNoField;
            }
            set
            {
                this.GSTNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HomeCurr
        {
            get
            {
                return this.HomeCurrField;
            }
            set
            {
                this.HomeCurrField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsCustByAgent
        {
            get
            {
                return this.IsCustByAgentField;
            }
            set
            {
                this.IsCustByAgentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsInclusive
        {
            get
            {
                return this.IsInclusiveField;
            }
            set
            {
                this.IsInclusiveField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool NoEditAfterPrint
        {
            get
            {
                return this.NoEditAfterPrintField;
            }
            set
            {
                this.NoEditAfterPrintField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prefix
        {
            get
            {
                return this.PrefixField;
            }
            set
            {
                this.PrefixField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RegNo
        {
            get
            {
                return this.RegNoField;
            }
            set
            {
                this.RegNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RunNo
        {
            get
            {
                return this.RunNoField;
            }
            set
            {
                this.RunNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SOPrefix
        {
            get
            {
                return this.SOPrefixField;
            }
            set
            {
                this.SOPrefixField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SORunNo
        {
            get
            {
                return this.SORunNoField;
            }
            set
            {
                this.SORunNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SalesTaxDec
        {
            get
            {
                return this.SalesTaxDecField;
            }
            set
            {
                this.SalesTaxDecField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ShowPrintTime
        {
            get
            {
                return this.ShowPrintTimeField;
            }
            set
            {
                this.ShowPrintTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SupportContat
        {
            get
            {
                return this.SupportContatField;
            }
            set
            {
                this.SupportContatField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tel
        {
            get
            {
                return this.TelField;
            }
            set
            {
                this.TelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WCFUrl
        {
            get
            {
                return this.WCFUrlField;
            }
            set
            {
                this.WCFUrlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WareHouse
        {
            get
            {
                return this.WareHouseField;
            }
            set
            {
                this.WareHouseField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OutLetBill", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceItem")]
    public partial class OutLetBill : object
    {
        
        private double AmountField;
        
        private string BranchCodeField;
        
        private string CNInvNoField;
        
        private string CompanyCodeField;
        
        private System.DateTime CreatedField;
        
        private string CustCodeField;
        
        private string ICodeField;
        
        private System.DateTime InvDateField;
        
        private string InvNoField;
        
        private bool IsInclusiveField;
        
        private double NetAmountField;
        
        private double QtyField;
        
        private double TaxAmtField;
        
        private string TaxGrpField;
        
        private string TrxTypeField;
        
        private double UPriceField;
        
        private string UserIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Amount
        {
            get
            {
                return this.AmountField;
            }
            set
            {
                this.AmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BranchCode
        {
            get
            {
                return this.BranchCodeField;
            }
            set
            {
                this.BranchCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CNInvNo
        {
            get
            {
                return this.CNInvNoField;
            }
            set
            {
                this.CNInvNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CompanyCode
        {
            get
            {
                return this.CompanyCodeField;
            }
            set
            {
                this.CompanyCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Created
        {
            get
            {
                return this.CreatedField;
            }
            set
            {
                this.CreatedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustCode
        {
            get
            {
                return this.CustCodeField;
            }
            set
            {
                this.CustCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ICode
        {
            get
            {
                return this.ICodeField;
            }
            set
            {
                this.ICodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime InvDate
        {
            get
            {
                return this.InvDateField;
            }
            set
            {
                this.InvDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InvNo
        {
            get
            {
                return this.InvNoField;
            }
            set
            {
                this.InvNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsInclusive
        {
            get
            {
                return this.IsInclusiveField;
            }
            set
            {
                this.IsInclusiveField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double NetAmount
        {
            get
            {
                return this.NetAmountField;
            }
            set
            {
                this.NetAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Qty
        {
            get
            {
                return this.QtyField;
            }
            set
            {
                this.QtyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double TaxAmt
        {
            get
            {
                return this.TaxAmtField;
            }
            set
            {
                this.TaxAmtField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TaxGrp
        {
            get
            {
                return this.TaxGrpField;
            }
            set
            {
                this.TaxGrpField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TrxType
        {
            get
            {
                return this.TrxTypeField;
            }
            set
            {
                this.TrxTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double UPrice
        {
            get
            {
                return this.UPriceField;
            }
            set
            {
                this.UPriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserID
        {
            get
            {
                return this.UserIDField;
            }
            set
            {
                this.UserIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RunnoInfo", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceItem")]
    public partial class RunnoInfo : object
    {
        
        private int MonthField;
        
        private int RunNoField;
        
        private string TrxtypeField;
        
        private int YearField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Month
        {
            get
            {
                return this.MonthField;
            }
            set
            {
                this.MonthField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RunNo
        {
            get
            {
                return this.RunNoField;
            }
            set
            {
                this.RunNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Trxtype
        {
            get
            {
                return this.TrxtypeField;
            }
            set
            {
                this.TrxtypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Year
        {
            get
            {
                return this.YearField;
            }
            set
            {
                this.YearField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IService1")]
public interface IService1
{
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/GetItems", ReplyAction="http://tempuri.org/IService1/GetItemsResponse")]
    System.IAsyncResult BeginGetItems(string comp, string bran, System.AsyncCallback callback, object asyncState);
    
    WcfServiceItem.CompositeType[] EndGetItems(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/GetItemCodes", ReplyAction="http://tempuri.org/IService1/GetItemCodesResponse")]
    System.IAsyncResult BeginGetItemCodes(string comp, string brn, System.AsyncCallback callback, object asyncState);
    
    WcfServiceItem.ItemCode[] EndGetItemCodes(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/GetCustomers", ReplyAction="http://tempuri.org/IService1/GetCustomersResponse")]
    System.IAsyncResult BeginGetCustomers(string comp, string brn, System.AsyncCallback callback, object asyncState);
    
    WcfServiceItem.Customer[] EndGetCustomers(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/GetCompProfile", ReplyAction="http://tempuri.org/IService1/GetCompProfileResponse")]
    System.IAsyncResult BeginGetCompProfile(string comp, string brn, string id, System.AsyncCallback callback, object asyncState);
    
    WcfServiceItem.CompanyProfile EndGetCompProfile(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/Login", ReplyAction="http://tempuri.org/IService1/LoginResponse")]
    System.IAsyncResult BeginLogin(string userid, string hashpass, string seccode, System.AsyncCallback callback, object asyncState);
    
    string EndLogin(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/LoginEx", ReplyAction="http://tempuri.org/IService1/LoginExResponse")]
    System.IAsyncResult BeginLoginEx(string userid, string hashpass, string seccode, string deviceid, System.AsyncCallback callback, object asyncState);
    
    string EndLoginEx(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/UploadOutletBills", ReplyAction="http://tempuri.org/IService1/UploadOutletBillsResponse")]
    System.IAsyncResult BeginUploadOutletBills(WcfServiceItem.OutLetBill[] list, string comp, string brn, string serail, string phoneno, System.AsyncCallback callback, object asyncState);
    
    string EndUploadOutletBills(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/GetRunno", ReplyAction="http://tempuri.org/IService1/GetRunnoResponse")]
    System.IAsyncResult BeginGetRunno(string comp, string brn, string userid, System.AsyncCallback callback, object asyncState);
    
    WcfServiceItem.RunnoInfo[] EndGetRunno(System.IAsyncResult result);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IService1Channel : IService1, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class GetItemsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    public GetItemsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
    {
        this.results = results;
    }
    
    public WcfServiceItem.CompositeType[] Result
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((WcfServiceItem.CompositeType[])(this.results[0]));
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class GetItemCodesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    public GetItemCodesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
    {
        this.results = results;
    }
    
    public WcfServiceItem.ItemCode[] Result
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((WcfServiceItem.ItemCode[])(this.results[0]));
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class GetCustomersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    public GetCustomersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
    {
        this.results = results;
    }
    
    public WcfServiceItem.Customer[] Result
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((WcfServiceItem.Customer[])(this.results[0]));
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class GetCompProfileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    public GetCompProfileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
    {
        this.results = results;
    }
    
    public WcfServiceItem.CompanyProfile Result
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((WcfServiceItem.CompanyProfile)(this.results[0]));
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class LoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    public LoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
    {
        this.results = results;
    }
    
    public string Result
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class LoginExCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    public LoginExCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
    {
        this.results = results;
    }
    
    public string Result
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class UploadOutletBillsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    public UploadOutletBillsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
    {
        this.results = results;
    }
    
    public string Result
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class GetRunnoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    public GetRunnoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
    {
        this.results = results;
    }
    
    public WcfServiceItem.RunnoInfo[] Result
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((WcfServiceItem.RunnoInfo[])(this.results[0]));
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class Service1Client : System.ServiceModel.ClientBase<IService1>, IService1
{
    
    private BeginOperationDelegate onBeginGetItemsDelegate;
    
    private EndOperationDelegate onEndGetItemsDelegate;
    
    private System.Threading.SendOrPostCallback onGetItemsCompletedDelegate;
    
    private BeginOperationDelegate onBeginGetItemCodesDelegate;
    
    private EndOperationDelegate onEndGetItemCodesDelegate;
    
    private System.Threading.SendOrPostCallback onGetItemCodesCompletedDelegate;
    
    private BeginOperationDelegate onBeginGetCustomersDelegate;
    
    private EndOperationDelegate onEndGetCustomersDelegate;
    
    private System.Threading.SendOrPostCallback onGetCustomersCompletedDelegate;
    
    private BeginOperationDelegate onBeginGetCompProfileDelegate;
    
    private EndOperationDelegate onEndGetCompProfileDelegate;
    
    private System.Threading.SendOrPostCallback onGetCompProfileCompletedDelegate;
    
    private BeginOperationDelegate onBeginLoginDelegate;
    
    private EndOperationDelegate onEndLoginDelegate;
    
    private System.Threading.SendOrPostCallback onLoginCompletedDelegate;
    
    private BeginOperationDelegate onBeginLoginExDelegate;
    
    private EndOperationDelegate onEndLoginExDelegate;
    
    private System.Threading.SendOrPostCallback onLoginExCompletedDelegate;
    
    private BeginOperationDelegate onBeginUploadOutletBillsDelegate;
    
    private EndOperationDelegate onEndUploadOutletBillsDelegate;
    
    private System.Threading.SendOrPostCallback onUploadOutletBillsCompletedDelegate;
    
    private BeginOperationDelegate onBeginGetRunnoDelegate;
    
    private EndOperationDelegate onEndGetRunnoDelegate;
    
    private System.Threading.SendOrPostCallback onGetRunnoCompletedDelegate;
    
    private BeginOperationDelegate onBeginOpenDelegate;
    
    private EndOperationDelegate onEndOpenDelegate;
    
    private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
    
    private BeginOperationDelegate onBeginCloseDelegate;
    
    private EndOperationDelegate onEndCloseDelegate;
    
    private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
    
    public Service1Client()
    {
    }
    
    public Service1Client(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public Service1Client(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public System.Net.CookieContainer CookieContainer
    {
        get
        {
            System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
            if ((httpCookieContainerManager != null))
            {
                return httpCookieContainerManager.CookieContainer;
            }
            else
            {
                return null;
            }
        }
        set
        {
            System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
            if ((httpCookieContainerManager != null))
            {
                httpCookieContainerManager.CookieContainer = value;
            }
            else
            {
                throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                        "ookieContainerBindingElement.");
            }
        }
    }
    
    public event System.EventHandler<GetItemsCompletedEventArgs> GetItemsCompleted;
    
    public event System.EventHandler<GetItemCodesCompletedEventArgs> GetItemCodesCompleted;
    
    public event System.EventHandler<GetCustomersCompletedEventArgs> GetCustomersCompleted;
    
    public event System.EventHandler<GetCompProfileCompletedEventArgs> GetCompProfileCompleted;
    
    public event System.EventHandler<LoginCompletedEventArgs> LoginCompleted;
    
    public event System.EventHandler<LoginExCompletedEventArgs> LoginExCompleted;
    
    public event System.EventHandler<UploadOutletBillsCompletedEventArgs> UploadOutletBillsCompleted;
    
    public event System.EventHandler<GetRunnoCompletedEventArgs> GetRunnoCompleted;
    
    public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
    
    public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult IService1.BeginGetItems(string comp, string bran, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginGetItems(comp, bran, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    WcfServiceItem.CompositeType[] IService1.EndGetItems(System.IAsyncResult result)
    {
        return base.Channel.EndGetItems(result);
    }
    
    private System.IAsyncResult OnBeginGetItems(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        string comp = ((string)(inValues[0]));
        string bran = ((string)(inValues[1]));
        return ((IService1)(this)).BeginGetItems(comp, bran, callback, asyncState);
    }
    
    private object[] OnEndGetItems(System.IAsyncResult result)
    {
        WcfServiceItem.CompositeType[] retVal = ((IService1)(this)).EndGetItems(result);
        return new object[] {
                retVal};
    }
    
    private void OnGetItemsCompleted(object state)
    {
        if ((this.GetItemsCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.GetItemsCompleted(this, new GetItemsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void GetItemsAsync(string comp, string bran)
    {
        this.GetItemsAsync(comp, bran, null);
    }
    
    public void GetItemsAsync(string comp, string bran, object userState)
    {
        if ((this.onBeginGetItemsDelegate == null))
        {
            this.onBeginGetItemsDelegate = new BeginOperationDelegate(this.OnBeginGetItems);
        }
        if ((this.onEndGetItemsDelegate == null))
        {
            this.onEndGetItemsDelegate = new EndOperationDelegate(this.OnEndGetItems);
        }
        if ((this.onGetItemsCompletedDelegate == null))
        {
            this.onGetItemsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetItemsCompleted);
        }
        base.InvokeAsync(this.onBeginGetItemsDelegate, new object[] {
                    comp,
                    bran}, this.onEndGetItemsDelegate, this.onGetItemsCompletedDelegate, userState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult IService1.BeginGetItemCodes(string comp, string brn, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginGetItemCodes(comp, brn, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    WcfServiceItem.ItemCode[] IService1.EndGetItemCodes(System.IAsyncResult result)
    {
        return base.Channel.EndGetItemCodes(result);
    }
    
    private System.IAsyncResult OnBeginGetItemCodes(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        string comp = ((string)(inValues[0]));
        string brn = ((string)(inValues[1]));
        return ((IService1)(this)).BeginGetItemCodes(comp, brn, callback, asyncState);
    }
    
    private object[] OnEndGetItemCodes(System.IAsyncResult result)
    {
        WcfServiceItem.ItemCode[] retVal = ((IService1)(this)).EndGetItemCodes(result);
        return new object[] {
                retVal};
    }
    
    private void OnGetItemCodesCompleted(object state)
    {
        if ((this.GetItemCodesCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.GetItemCodesCompleted(this, new GetItemCodesCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void GetItemCodesAsync(string comp, string brn)
    {
        this.GetItemCodesAsync(comp, brn, null);
    }
    
    public void GetItemCodesAsync(string comp, string brn, object userState)
    {
        if ((this.onBeginGetItemCodesDelegate == null))
        {
            this.onBeginGetItemCodesDelegate = new BeginOperationDelegate(this.OnBeginGetItemCodes);
        }
        if ((this.onEndGetItemCodesDelegate == null))
        {
            this.onEndGetItemCodesDelegate = new EndOperationDelegate(this.OnEndGetItemCodes);
        }
        if ((this.onGetItemCodesCompletedDelegate == null))
        {
            this.onGetItemCodesCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetItemCodesCompleted);
        }
        base.InvokeAsync(this.onBeginGetItemCodesDelegate, new object[] {
                    comp,
                    brn}, this.onEndGetItemCodesDelegate, this.onGetItemCodesCompletedDelegate, userState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult IService1.BeginGetCustomers(string comp, string brn, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginGetCustomers(comp, brn, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    WcfServiceItem.Customer[] IService1.EndGetCustomers(System.IAsyncResult result)
    {
        return base.Channel.EndGetCustomers(result);
    }
    
    private System.IAsyncResult OnBeginGetCustomers(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        string comp = ((string)(inValues[0]));
        string brn = ((string)(inValues[1]));
        return ((IService1)(this)).BeginGetCustomers(comp, brn, callback, asyncState);
    }
    
    private object[] OnEndGetCustomers(System.IAsyncResult result)
    {
        WcfServiceItem.Customer[] retVal = ((IService1)(this)).EndGetCustomers(result);
        return new object[] {
                retVal};
    }
    
    private void OnGetCustomersCompleted(object state)
    {
        if ((this.GetCustomersCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.GetCustomersCompleted(this, new GetCustomersCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void GetCustomersAsync(string comp, string brn)
    {
        this.GetCustomersAsync(comp, brn, null);
    }
    
    public void GetCustomersAsync(string comp, string brn, object userState)
    {
        if ((this.onBeginGetCustomersDelegate == null))
        {
            this.onBeginGetCustomersDelegate = new BeginOperationDelegate(this.OnBeginGetCustomers);
        }
        if ((this.onEndGetCustomersDelegate == null))
        {
            this.onEndGetCustomersDelegate = new EndOperationDelegate(this.OnEndGetCustomers);
        }
        if ((this.onGetCustomersCompletedDelegate == null))
        {
            this.onGetCustomersCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetCustomersCompleted);
        }
        base.InvokeAsync(this.onBeginGetCustomersDelegate, new object[] {
                    comp,
                    brn}, this.onEndGetCustomersDelegate, this.onGetCustomersCompletedDelegate, userState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult IService1.BeginGetCompProfile(string comp, string brn, string id, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginGetCompProfile(comp, brn, id, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    WcfServiceItem.CompanyProfile IService1.EndGetCompProfile(System.IAsyncResult result)
    {
        return base.Channel.EndGetCompProfile(result);
    }
    
    private System.IAsyncResult OnBeginGetCompProfile(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        string comp = ((string)(inValues[0]));
        string brn = ((string)(inValues[1]));
        string id = ((string)(inValues[2]));
        return ((IService1)(this)).BeginGetCompProfile(comp, brn, id, callback, asyncState);
    }
    
    private object[] OnEndGetCompProfile(System.IAsyncResult result)
    {
        WcfServiceItem.CompanyProfile retVal = ((IService1)(this)).EndGetCompProfile(result);
        return new object[] {
                retVal};
    }
    
    private void OnGetCompProfileCompleted(object state)
    {
        if ((this.GetCompProfileCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.GetCompProfileCompleted(this, new GetCompProfileCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void GetCompProfileAsync(string comp, string brn, string id)
    {
        this.GetCompProfileAsync(comp, brn, id, null);
    }
    
    public void GetCompProfileAsync(string comp, string brn, string id, object userState)
    {
        if ((this.onBeginGetCompProfileDelegate == null))
        {
            this.onBeginGetCompProfileDelegate = new BeginOperationDelegate(this.OnBeginGetCompProfile);
        }
        if ((this.onEndGetCompProfileDelegate == null))
        {
            this.onEndGetCompProfileDelegate = new EndOperationDelegate(this.OnEndGetCompProfile);
        }
        if ((this.onGetCompProfileCompletedDelegate == null))
        {
            this.onGetCompProfileCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetCompProfileCompleted);
        }
        base.InvokeAsync(this.onBeginGetCompProfileDelegate, new object[] {
                    comp,
                    brn,
                    id}, this.onEndGetCompProfileDelegate, this.onGetCompProfileCompletedDelegate, userState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult IService1.BeginLogin(string userid, string hashpass, string seccode, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginLogin(userid, hashpass, seccode, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    string IService1.EndLogin(System.IAsyncResult result)
    {
        return base.Channel.EndLogin(result);
    }
    
    private System.IAsyncResult OnBeginLogin(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        string userid = ((string)(inValues[0]));
        string hashpass = ((string)(inValues[1]));
        string seccode = ((string)(inValues[2]));
        return ((IService1)(this)).BeginLogin(userid, hashpass, seccode, callback, asyncState);
    }
    
    private object[] OnEndLogin(System.IAsyncResult result)
    {
        string retVal = ((IService1)(this)).EndLogin(result);
        return new object[] {
                retVal};
    }
    
    private void OnLoginCompleted(object state)
    {
        if ((this.LoginCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.LoginCompleted(this, new LoginCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void LoginAsync(string userid, string hashpass, string seccode)
    {
        this.LoginAsync(userid, hashpass, seccode, null);
    }
    
    public void LoginAsync(string userid, string hashpass, string seccode, object userState)
    {
        if ((this.onBeginLoginDelegate == null))
        {
            this.onBeginLoginDelegate = new BeginOperationDelegate(this.OnBeginLogin);
        }
        if ((this.onEndLoginDelegate == null))
        {
            this.onEndLoginDelegate = new EndOperationDelegate(this.OnEndLogin);
        }
        if ((this.onLoginCompletedDelegate == null))
        {
            this.onLoginCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnLoginCompleted);
        }
        base.InvokeAsync(this.onBeginLoginDelegate, new object[] {
                    userid,
                    hashpass,
                    seccode}, this.onEndLoginDelegate, this.onLoginCompletedDelegate, userState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult IService1.BeginLoginEx(string userid, string hashpass, string seccode, string deviceid, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginLoginEx(userid, hashpass, seccode, deviceid, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    string IService1.EndLoginEx(System.IAsyncResult result)
    {
        return base.Channel.EndLoginEx(result);
    }
    
    private System.IAsyncResult OnBeginLoginEx(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        string userid = ((string)(inValues[0]));
        string hashpass = ((string)(inValues[1]));
        string seccode = ((string)(inValues[2]));
        string deviceid = ((string)(inValues[3]));
        return ((IService1)(this)).BeginLoginEx(userid, hashpass, seccode, deviceid, callback, asyncState);
    }
    
    private object[] OnEndLoginEx(System.IAsyncResult result)
    {
        string retVal = ((IService1)(this)).EndLoginEx(result);
        return new object[] {
                retVal};
    }
    
    private void OnLoginExCompleted(object state)
    {
        if ((this.LoginExCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.LoginExCompleted(this, new LoginExCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void LoginExAsync(string userid, string hashpass, string seccode, string deviceid)
    {
        this.LoginExAsync(userid, hashpass, seccode, deviceid, null);
    }
    
    public void LoginExAsync(string userid, string hashpass, string seccode, string deviceid, object userState)
    {
        if ((this.onBeginLoginExDelegate == null))
        {
            this.onBeginLoginExDelegate = new BeginOperationDelegate(this.OnBeginLoginEx);
        }
        if ((this.onEndLoginExDelegate == null))
        {
            this.onEndLoginExDelegate = new EndOperationDelegate(this.OnEndLoginEx);
        }
        if ((this.onLoginExCompletedDelegate == null))
        {
            this.onLoginExCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnLoginExCompleted);
        }
        base.InvokeAsync(this.onBeginLoginExDelegate, new object[] {
                    userid,
                    hashpass,
                    seccode,
                    deviceid}, this.onEndLoginExDelegate, this.onLoginExCompletedDelegate, userState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult IService1.BeginUploadOutletBills(WcfServiceItem.OutLetBill[] list, string comp, string brn, string serail, string phoneno, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginUploadOutletBills(list, comp, brn, serail, phoneno, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    string IService1.EndUploadOutletBills(System.IAsyncResult result)
    {
        return base.Channel.EndUploadOutletBills(result);
    }
    
    private System.IAsyncResult OnBeginUploadOutletBills(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        WcfServiceItem.OutLetBill[] list = ((WcfServiceItem.OutLetBill[])(inValues[0]));
        string comp = ((string)(inValues[1]));
        string brn = ((string)(inValues[2]));
        string serail = ((string)(inValues[3]));
        string phoneno = ((string)(inValues[4]));
        return ((IService1)(this)).BeginUploadOutletBills(list, comp, brn, serail, phoneno, callback, asyncState);
    }
    
    private object[] OnEndUploadOutletBills(System.IAsyncResult result)
    {
        string retVal = ((IService1)(this)).EndUploadOutletBills(result);
        return new object[] {
                retVal};
    }
    
    private void OnUploadOutletBillsCompleted(object state)
    {
        if ((this.UploadOutletBillsCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.UploadOutletBillsCompleted(this, new UploadOutletBillsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void UploadOutletBillsAsync(WcfServiceItem.OutLetBill[] list, string comp, string brn, string serail, string phoneno)
    {
        this.UploadOutletBillsAsync(list, comp, brn, serail, phoneno, null);
    }
    
    public void UploadOutletBillsAsync(WcfServiceItem.OutLetBill[] list, string comp, string brn, string serail, string phoneno, object userState)
    {
        if ((this.onBeginUploadOutletBillsDelegate == null))
        {
            this.onBeginUploadOutletBillsDelegate = new BeginOperationDelegate(this.OnBeginUploadOutletBills);
        }
        if ((this.onEndUploadOutletBillsDelegate == null))
        {
            this.onEndUploadOutletBillsDelegate = new EndOperationDelegate(this.OnEndUploadOutletBills);
        }
        if ((this.onUploadOutletBillsCompletedDelegate == null))
        {
            this.onUploadOutletBillsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnUploadOutletBillsCompleted);
        }
        base.InvokeAsync(this.onBeginUploadOutletBillsDelegate, new object[] {
                    list,
                    comp,
                    brn,
                    serail,
                    phoneno}, this.onEndUploadOutletBillsDelegate, this.onUploadOutletBillsCompletedDelegate, userState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult IService1.BeginGetRunno(string comp, string brn, string userid, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginGetRunno(comp, brn, userid, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    WcfServiceItem.RunnoInfo[] IService1.EndGetRunno(System.IAsyncResult result)
    {
        return base.Channel.EndGetRunno(result);
    }
    
    private System.IAsyncResult OnBeginGetRunno(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        string comp = ((string)(inValues[0]));
        string brn = ((string)(inValues[1]));
        string userid = ((string)(inValues[2]));
        return ((IService1)(this)).BeginGetRunno(comp, brn, userid, callback, asyncState);
    }
    
    private object[] OnEndGetRunno(System.IAsyncResult result)
    {
        WcfServiceItem.RunnoInfo[] retVal = ((IService1)(this)).EndGetRunno(result);
        return new object[] {
                retVal};
    }
    
    private void OnGetRunnoCompleted(object state)
    {
        if ((this.GetRunnoCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.GetRunnoCompleted(this, new GetRunnoCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void GetRunnoAsync(string comp, string brn, string userid)
    {
        this.GetRunnoAsync(comp, brn, userid, null);
    }
    
    public void GetRunnoAsync(string comp, string brn, string userid, object userState)
    {
        if ((this.onBeginGetRunnoDelegate == null))
        {
            this.onBeginGetRunnoDelegate = new BeginOperationDelegate(this.OnBeginGetRunno);
        }
        if ((this.onEndGetRunnoDelegate == null))
        {
            this.onEndGetRunnoDelegate = new EndOperationDelegate(this.OnEndGetRunno);
        }
        if ((this.onGetRunnoCompletedDelegate == null))
        {
            this.onGetRunnoCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetRunnoCompleted);
        }
        base.InvokeAsync(this.onBeginGetRunnoDelegate, new object[] {
                    comp,
                    brn,
                    userid}, this.onEndGetRunnoDelegate, this.onGetRunnoCompletedDelegate, userState);
    }
    
    private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
    }
    
    private object[] OnEndOpen(System.IAsyncResult result)
    {
        ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
        return null;
    }
    
    private void OnOpenCompleted(object state)
    {
        if ((this.OpenCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void OpenAsync()
    {
        this.OpenAsync(null);
    }
    
    public void OpenAsync(object userState)
    {
        if ((this.onBeginOpenDelegate == null))
        {
            this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
        }
        if ((this.onEndOpenDelegate == null))
        {
            this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
        }
        if ((this.onOpenCompletedDelegate == null))
        {
            this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
        }
        base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
    }
    
    private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
    }
    
    private object[] OnEndClose(System.IAsyncResult result)
    {
        ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
        return null;
    }
    
    private void OnCloseCompleted(object state)
    {
        if ((this.CloseCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void CloseAsync()
    {
        this.CloseAsync(null);
    }
    
    public void CloseAsync(object userState)
    {
        if ((this.onBeginCloseDelegate == null))
        {
            this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
        }
        if ((this.onEndCloseDelegate == null))
        {
            this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
        }
        if ((this.onCloseCompletedDelegate == null))
        {
            this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
        }
        base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
    }
    
    protected override IService1 CreateChannel()
    {
        return new Service1ClientChannel(this);
    }
    
    private class Service1ClientChannel : ChannelBase<IService1>, IService1
    {
        
        public Service1ClientChannel(System.ServiceModel.ClientBase<IService1> client) : 
                base(client)
        {
        }
        
        public System.IAsyncResult BeginGetItems(string comp, string bran, System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[2];
            _args[0] = comp;
            _args[1] = bran;
            System.IAsyncResult _result = base.BeginInvoke("GetItems", _args, callback, asyncState);
            return _result;
        }
        
        public WcfServiceItem.CompositeType[] EndGetItems(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            WcfServiceItem.CompositeType[] _result = ((WcfServiceItem.CompositeType[])(base.EndInvoke("GetItems", _args, result)));
            return _result;
        }
        
        public System.IAsyncResult BeginGetItemCodes(string comp, string brn, System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[2];
            _args[0] = comp;
            _args[1] = brn;
            System.IAsyncResult _result = base.BeginInvoke("GetItemCodes", _args, callback, asyncState);
            return _result;
        }
        
        public WcfServiceItem.ItemCode[] EndGetItemCodes(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            WcfServiceItem.ItemCode[] _result = ((WcfServiceItem.ItemCode[])(base.EndInvoke("GetItemCodes", _args, result)));
            return _result;
        }
        
        public System.IAsyncResult BeginGetCustomers(string comp, string brn, System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[2];
            _args[0] = comp;
            _args[1] = brn;
            System.IAsyncResult _result = base.BeginInvoke("GetCustomers", _args, callback, asyncState);
            return _result;
        }
        
        public WcfServiceItem.Customer[] EndGetCustomers(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            WcfServiceItem.Customer[] _result = ((WcfServiceItem.Customer[])(base.EndInvoke("GetCustomers", _args, result)));
            return _result;
        }
        
        public System.IAsyncResult BeginGetCompProfile(string comp, string brn, string id, System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[3];
            _args[0] = comp;
            _args[1] = brn;
            _args[2] = id;
            System.IAsyncResult _result = base.BeginInvoke("GetCompProfile", _args, callback, asyncState);
            return _result;
        }
        
        public WcfServiceItem.CompanyProfile EndGetCompProfile(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            WcfServiceItem.CompanyProfile _result = ((WcfServiceItem.CompanyProfile)(base.EndInvoke("GetCompProfile", _args, result)));
            return _result;
        }
        
        public System.IAsyncResult BeginLogin(string userid, string hashpass, string seccode, System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[3];
            _args[0] = userid;
            _args[1] = hashpass;
            _args[2] = seccode;
            System.IAsyncResult _result = base.BeginInvoke("Login", _args, callback, asyncState);
            return _result;
        }
        
        public string EndLogin(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            string _result = ((string)(base.EndInvoke("Login", _args, result)));
            return _result;
        }
        
        public System.IAsyncResult BeginLoginEx(string userid, string hashpass, string seccode, string deviceid, System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[4];
            _args[0] = userid;
            _args[1] = hashpass;
            _args[2] = seccode;
            _args[3] = deviceid;
            System.IAsyncResult _result = base.BeginInvoke("LoginEx", _args, callback, asyncState);
            return _result;
        }
        
        public string EndLoginEx(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            string _result = ((string)(base.EndInvoke("LoginEx", _args, result)));
            return _result;
        }
        
        public System.IAsyncResult BeginUploadOutletBills(WcfServiceItem.OutLetBill[] list, string comp, string brn, string serail, string phoneno, System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[5];
            _args[0] = list;
            _args[1] = comp;
            _args[2] = brn;
            _args[3] = serail;
            _args[4] = phoneno;
            System.IAsyncResult _result = base.BeginInvoke("UploadOutletBills", _args, callback, asyncState);
            return _result;
        }
        
        public string EndUploadOutletBills(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            string _result = ((string)(base.EndInvoke("UploadOutletBills", _args, result)));
            return _result;
        }
        
        public System.IAsyncResult BeginGetRunno(string comp, string brn, string userid, System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[3];
            _args[0] = comp;
            _args[1] = brn;
            _args[2] = userid;
            System.IAsyncResult _result = base.BeginInvoke("GetRunno", _args, callback, asyncState);
            return _result;
        }
        
        public WcfServiceItem.RunnoInfo[] EndGetRunno(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            WcfServiceItem.RunnoInfo[] _result = ((WcfServiceItem.RunnoInfo[])(base.EndInvoke("GetRunno", _args, result)));
            return _result;
        }
    }
}
