#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("wincom.mobile.erp.Resource", IsApplication=true)]

namespace wincom.mobile.erp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040008
			public const int ab_background = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int ab_bottom_shadow_1 = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int ab_bottom_shadow_2 = 2130968586;
			
			// aapt resource value: 0x7f040007
			public const int action_bar_title_color = 2130968583;
			
			// aapt resource value: 0x7f04000b
			public const int btn_bg_color = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int btn_bg_shadow_color = 2130968588;
			
			// aapt resource value: 0x7f040006
			public const int main_background = 2130968582;
			
			// aapt resource value: 0x7f040001
			public const int xam_blue = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int xam_dark_blue = 2130968578;
			
			// aapt resource value: 0x7f040004
			public const int xam_gray = 2130968580;
			
			// aapt resource value: 0x7f040003
			public const int xam_green = 2130968579;
			
			// aapt resource value: 0x7f040005
			public const int xam_light_gray = 2130968581;
			
			// aapt resource value: 0x7f040000
			public const int xam_purple = 2130968576;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060000
			public const int btn_corner_radius = 2131099648;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ab_background = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int about = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int add = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int btn_bg = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int btn_bg_inactive = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int btn_bg_normal = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int btn_bg_pressed = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int create = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int discrete_shadow = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int download = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int even_row = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int exit = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int ic_action_logo = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int Icon = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int item = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int left = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int listview_selector_even = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int listview_selector_odd = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int odd_row = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int ok = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int shop = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int shoplist = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int trader = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int upload = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int wrench = 2130837528;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f090045
			public const int Amount = 2131296325;
			
			// aapt resource value: 0x7f090020
			public const int Cancel = 2131296288;
			
			// aapt resource value: 0x7f090041
			public const int CustList = 2131296321;
			
			// aapt resource value: 0x7f090034
			public const int ICodeList = 2131296308;
			
			// aapt resource value: 0x7f09001f
			public const int Save = 2131296287;
			
			// aapt resource value: 0x7f090000
			public const int about_credits = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int about_descrip = 2131296257;
			
			// aapt resource value: 0x7f090008
			public const int ad_Cancel = 2131296264;
			
			// aapt resource value: 0x7f090007
			public const int ad_bSave = 2131296263;
			
			// aapt resource value: 0x7f09006a
			public const int add = 2131296362;
			
			// aapt resource value: 0x7f09003b
			public const int btnItem_OK = 2131296315;
			
			// aapt resource value: 0x7f090063
			public const int btnTrd_OK = 2131296355;
			
			// aapt resource value: 0x7f090050
			public const int butAbout = 2131296336;
			
			// aapt resource value: 0x7f090040
			public const int butCustBack = 2131296320;
			
			// aapt resource value: 0x7f09004c
			public const int butCustProf = 2131296332;
			
			// aapt resource value: 0x7f09004d
			public const int butDown = 2131296333;
			
			// aapt resource value: 0x7f09004e
			public const int butDownCust = 2131296334;
			
			// aapt resource value: 0x7f090033
			public const int butICodeBack = 2131296307;
			
			// aapt resource value: 0x7f090046
			public const int butInvBack = 2131296326;
			
			// aapt resource value: 0x7f090029
			public const int butInvItmBack = 2131296297;
			
			// aapt resource value: 0x7f09004a
			public const int butInvlist = 2131296330;
			
			// aapt resource value: 0x7f09004b
			public const int butMaster = 2131296331;
			
			// aapt resource value: 0x7f090051
			public const int butOut = 2131296337;
			
			// aapt resource value: 0x7f090049
			public const int butSecond = 2131296329;
			
			// aapt resource value: 0x7f090047
			public const int butnewInv = 2131296327;
			
			// aapt resource value: 0x7f09002a
			public const int butnewItem = 2131296298;
			
			// aapt resource value: 0x7f090054
			public const int button1 = 2131296340;
			
			// aapt resource value: 0x7f09004f
			public const int butupload = 2131296335;
			
			// aapt resource value: 0x7f09006d
			public const int call = 2131296365;
			
			// aapt resource value: 0x7f09003c
			public const int custcode = 2131296316;
			
			// aapt resource value: 0x7f09003d
			public const int custname = 2131296317;
			
			// aapt resource value: 0x7f090052
			public const int editText1 = 2131296338;
			
			// aapt resource value: 0x7f090059
			public const int exit = 2131296345;
			
			// aapt resource value: 0x7f090048
			public const int feedList = 2131296328;
			
			// aapt resource value: 0x7f09002d
			public const int icodecode = 2131296301;
			
			// aapt resource value: 0x7f09002c
			public const int icodedesc = 2131296300;
			
			// aapt resource value: 0x7f090031
			public const int icodeinclusive = 2131296305;
			
			// aapt resource value: 0x7f09002e
			public const int icodeprice = 2131296302;
			
			// aapt resource value: 0x7f09002f
			public const int icodetax = 2131296303;
			
			// aapt resource value: 0x7f090030
			public const int icodetaxper = 2131296304;
			
			// aapt resource value: 0x7f090044
			public const int invcust = 2131296324;
			
			// aapt resource value: 0x7f090042
			public const int invdate = 2131296322;
			
			// aapt resource value: 0x7f09002b
			public const int invitemList = 2131296299;
			
			// aapt resource value: 0x7f090028
			public const int invitemamt = 2131296296;
			
			// aapt resource value: 0x7f090023
			public const int invitemcode = 2131296291;
			
			// aapt resource value: 0x7f090021
			public const int invitemdesc = 2131296289;
			
			// aapt resource value: 0x7f090025
			public const int invitemprice = 2131296293;
			
			// aapt resource value: 0x7f090024
			public const int invitemqty = 2131296292;
			
			// aapt resource value: 0x7f090027
			public const int invitemtax = 2131296295;
			
			// aapt resource value: 0x7f090026
			public const int invitemtaxgrp = 2131296294;
			
			// aapt resource value: 0x7f090043
			public const int invno = 2131296323;
			
			// aapt resource value: 0x7f090002
			public const int lbinvno = 2131296258;
			
			// aapt resource value: 0x7f090022
			public const int linearLayout1 = 2131296290;
			
			// aapt resource value: 0x7f090058
			public const int login = 2131296344;
			
			// aapt resource value: 0x7f090057
			public const int login_code = 2131296343;
			
			// aapt resource value: 0x7f090056
			public const int login_password = 2131296342;
			
			// aapt resource value: 0x7f090055
			public const int login_userName = 2131296341;
			
			// aapt resource value: 0x7f090069
			public const int mainMenu = 2131296361;
			
			// aapt resource value: 0x7f090065
			public const int mmenu_back = 2131296357;
			
			// aapt resource value: 0x7f090066
			public const int mmenu_clear = 2131296358;
			
			// aapt resource value: 0x7f090064
			public const int mmenu_downcompinfo = 2131296356;
			
			// aapt resource value: 0x7f090068
			public const int mmenu_logoff = 2131296360;
			
			// aapt resource value: 0x7f090067
			public const int mmenu_setting = 2131296359;
			
			// aapt resource value: 0x7f09000e
			public const int newinv_bsave = 2131296270;
			
			// aapt resource value: 0x7f09000f
			public const int newinv_cancel = 2131296271;
			
			// aapt resource value: 0x7f09000c
			public const int newinv_custcode = 2131296268;
			
			// aapt resource value: 0x7f09000d
			public const int newinv_custname = 2131296269;
			
			// aapt resource value: 0x7f09000a
			public const int newinv_date = 2131296266;
			
			// aapt resource value: 0x7f09000b
			public const int newinv_no = 2131296267;
			
			// aapt resource value: 0x7f090053
			public const int numberPicker1 = 2131296339;
			
			// aapt resource value: 0x7f09006b
			public const int phone = 2131296363;
			
			// aapt resource value: 0x7f09006f
			public const int popInvadd = 2131296367;
			
			// aapt resource value: 0x7f090070
			public const int popInvdelete = 2131296368;
			
			// aapt resource value: 0x7f090071
			public const int popInvprint = 2131296369;
			
			// aapt resource value: 0x7f090072
			public const int popadd = 2131296370;
			
			// aapt resource value: 0x7f090074
			public const int popdelete = 2131296372;
			
			// aapt resource value: 0x7f090073
			public const int popedit = 2131296371;
			
			// aapt resource value: 0x7f09006e
			public const int refresh = 2131296366;
			
			// aapt resource value: 0x7f09006c
			public const int submenu = 2131296364;
			
			// aapt resource value: 0x7f090005
			public const int tableLayout1 = 2131296261;
			
			// aapt resource value: 0x7f090032
			public const int tableLayoutItem = 2131296306;
			
			// aapt resource value: 0x7f09003e
			public const int tableLayoutItemc = 2131296318;
			
			// aapt resource value: 0x7f090006
			public const int tableRow1 = 2131296262;
			
			// aapt resource value: 0x7f09003f
			public const int tableRow1c = 2131296319;
			
			// aapt resource value: 0x7f090009
			public const int tableRow2 = 2131296265;
			
			// aapt resource value: 0x7f090012
			public const int textView1 = 2131296274;
			
			// aapt resource value: 0x7f090014
			public const int textView2 = 2131296276;
			
			// aapt resource value: 0x7f09001a
			public const int textView4 = 2131296282;
			
			// aapt resource value: 0x7f090016
			public const int textView5 = 2131296278;
			
			// aapt resource value: 0x7f090011
			public const int txtInvcust = 2131296273;
			
			// aapt resource value: 0x7f090010
			public const int txtInvnp = 2131296272;
			
			// aapt resource value: 0x7f090004
			public const int txtad_prefix = 2131296260;
			
			// aapt resource value: 0x7f090003
			public const int txtad_printer = 2131296259;
			
			// aapt resource value: 0x7f09001e
			public const int txtamount = 2131296286;
			
			// aapt resource value: 0x7f090013
			public const int txtcode = 2131296275;
			
			// aapt resource value: 0x7f09005c
			public const int txtcust_addr1 = 2131296348;
			
			// aapt resource value: 0x7f09005d
			public const int txtcust_addr2 = 2131296349;
			
			// aapt resource value: 0x7f09005e
			public const int txtcust_addr3 = 2131296350;
			
			// aapt resource value: 0x7f09005f
			public const int txtcust_addr4 = 2131296351;
			
			// aapt resource value: 0x7f09005a
			public const int txtcust_code = 2131296346;
			
			// aapt resource value: 0x7f090061
			public const int txtcust_fax = 2131296353;
			
			// aapt resource value: 0x7f090062
			public const int txtcust_gst = 2131296354;
			
			// aapt resource value: 0x7f09005b
			public const int txtcust_name = 2131296347;
			
			// aapt resource value: 0x7f090060
			public const int txtcust_tel = 2131296352;
			
			// aapt resource value: 0x7f090015
			public const int txtdesc = 2131296277;
			
			// aapt resource value: 0x7f090019
			public const int txtinvisincl = 2131296281;
			
			// aapt resource value: 0x7f090018
			public const int txtinvtaxper = 2131296280;
			
			// aapt resource value: 0x7f090036
			public const int txtitem_code = 2131296310;
			
			// aapt resource value: 0x7f090035
			public const int txtitem_desc = 2131296309;
			
			// aapt resource value: 0x7f09003a
			public const int txtitem_incl = 2131296314;
			
			// aapt resource value: 0x7f090037
			public const int txtitem_price = 2131296311;
			
			// aapt resource value: 0x7f090039
			public const int txtitem_tax = 2131296313;
			
			// aapt resource value: 0x7f090038
			public const int txtitem_taxgrop = 2131296312;
			
			// aapt resource value: 0x7f09001c
			public const int txtprice = 2131296284;
			
			// aapt resource value: 0x7f09001b
			public const int txtqty = 2131296283;
			
			// aapt resource value: 0x7f090017
			public const int txttax = 2131296279;
			
			// aapt resource value: 0x7f09001d
			public const int txttaxamt = 2131296285;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int About = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int AdPara = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int CreateInvoice = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Entry = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int InvDtlItemView = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int InvDtlView = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int ItemCodeDtlList = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int ItemCodeEntry = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int ItemCodeList = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int ItemInfo = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int ListCustDtlView = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int ListCustView = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int ListItemRow = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int ListView = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int Main = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int Second = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int SignIn = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int spinner_item = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int TraderInfo = 2130903058;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f080000
			public const int MainMenu = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int menu = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int popupInv = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int popupItem = 2131230723;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050002
			public const int app_credits = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int app_descrip = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070001
			public const int XamActionBarStyle = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int XamActionBarTheme = 2131165184;
			
			// aapt resource value: 0x7f070002
			public const int XamActionBarTitleStyle = 2131165186;
			
			// aapt resource value: 0x7f070005
			public const int XamButton = 2131165189;
			
			// aapt resource value: 0x7f070004
			public const int XamSubtitleText = 2131165188;
			
			// aapt resource value: 0x7f070003
			public const int XamTitleText = 2131165187;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
